### ISSUE TITLE
Les événements futurs ne sont pas affichés

### ISSUE THREAD

**Issue by jihaisse** [Chambe-Carnet/cc-sync#10]
Seul les événements passés sont listés dans le tableau.

**Comment by jihaisse** [comment]
En fait, si.
Il faut qu'il y ait au minimum 1 inscrit.
Est-ce possible d'afficher tous les événements même s'il n'y a pas d'inscrits ?

**Comment by crazy-seb** [comment]
Pull Reqest #11
