### ISSUE TITLE
Création de l'utilisateur sans rôle

### ISSUE THREAD

**Issue by jihaisse** [Chambe-Carnet/cc-sync#2]
Lors de la création automatique des utilisateurs, ceux-ci ont par défaut le rôle "Abonné", il ne faudrait pas leur donner de rôle.

![capture d ecran 2017-06-08 a 09 56 25](https://user-images.githubusercontent.com/498003/26918081-c99b939c-4c30-11e7-9eec-d459b39931f7.png)

**Comment by crazy-seb** [comment]
Pull Request #7
