### ISSUE TITLE
Listing des events

### ISSUE THREAD

**Issue by crazy-seb** [Chambe-Carnet/cc-sync#20]
Le nombre de participants n'est pas toujours exact (cf. events adhésions)

**Comment by jihaisse** [comment]
J'ai regardé un peu...
Quand j'appelle l'API en curl, ça me retourne bien le bon nombre de participants.
Par contre, dans PHP, j'ai fait afficher l'objet response, on a pas le même nombre...
Il faudrait regarder au niveau de Gruzzle...
