### ISSUE TITLE
Génération des badges

### ISSUE THREAD

**Issue by jihaisse** [Chambe-Carnet/cc-sync#27]
Comme on génère la liste CSV des participants, il faudrait pouvoir générer les badges en PDF.

Il faut les infos suivantes : 
1. Prénom
2. Nom
3. Profession
4. Le nom de l'event

![badges-1](https://user-images.githubusercontent.com/498003/46945238-90dd3500-d074-11e8-8537-66851a9eeee7.jpg)

**Comment by jihaisse** [comment]
Voilà un exemple de badge.
Il est en recto/verso

![badges-1](https://user-images.githubusercontent.com/498003/46945073-2d530780-d074-11e8-802f-c812ab46f00b.jpg)

**Comment by crazy-seb** [comment]
cf Pull Request #29 

Pour l'instant j'ai seulement crée un fichier html que j'ouvre en automatique dans un nouvel onglet.
Il y a un badge par page si tu imprimes directement le fichier html.
Par contre il me faut la police de caractère utilisé pour finaliser.

**Comment by jihaisse** [comment]
Je viens de tester, c'est classe !
J'ai repéré quelques soucis : 

1. L'image est trop grande, si on imprime comme ça, ça ne va pas rentrer dans les pochettes
2. Le texte apparait en noir
3. On peut mettre "normalement" 3 badges par feuille A4

Les fonts sont ici : https://drive.google.com/drive/folders/0B221fxnbj1d4WUpodzdMZ0MweWM?usp=sharing

J'ai changé la taille de l'image et mis un svg à la place du jpg pour avoir une meilleur qualité.
N'oublie pas de faire un update avant de modifier :)

**Comment by crazy-seb** [comment]
cf Pull Request #30 

J'ai ajouté la police et corrigé les pages breaks des badges.
J'ai aussi revu la structure du plugin pour qu'elle soit plus propre.

Pour le texte en noir, c'est les navigateurs qui ne gardent pas les couleurs en fonction de ta configuration de mise en page d'impression.
Sur ce point, on touche la limite de l'impression de page html. Si on veut être sûr de ce qu'on imprime, quelque soit la configuration du navigateur, il faut générer un pdf (mais c'est un peu plus chiant à faire et tous les styles/fonts/images peuvent ne pas être pris en compte...).

**Comment by jihaisse** [comment]
J'ai oublié de faire afficher sur le badge la société.

1. Prénom
2. Nom
3. **Société**
4. Profession
5. Le nom de l'event

**Comment by crazy-seb** [comment]
cf Pull Request #31

**Comment by jihaisse** [comment]
J'ai modifié l'ordre des champs (inversion entre nom/prénom et société/fonction).
J'ai revu la taille des typos du coup.

Ça me semble bon. Je ferme l'issue et je valide avec Marlène.

Good Job Seb !
