### ISSUE TITLE
Nom de famille de l'utilisateur en minuscule avec première lettre en majuscule

### ISSUE THREAD

**Issue by jihaisse** [Chambe-Carnet/cc-sync#3]
Le nom de famille dans weezevent est en majuscule, il faudrait le mettre en minuscule avec la première lettre en majuscule

**Comment by jihaisse** [comment]
![capture d ecran 2017-06-08 a 10 02 14](https://user-images.githubusercontent.com/498003/26918280-9623c22c-4c31-11e7-95ad-05ffebc7e6cf.png)

**Comment by crazy-seb** [comment]
Pull Request #7
