### ISSUE TITLE
Récupérer les informations complémentaires de weezevent

### ISSUE THREAD

**Issue by jihaisse** [Chambe-Carnet/cc-sync#4]
Lors de l'inscription, on demande la profession, l'entreprise, twitter, linkedin, etc...
Ça serait top de les récupérer dans le profil de l'utilisateur.

![capture d ecran 2017-06-08 a 10 02 48](https://user-images.githubusercontent.com/498003/26918323-cda9cf3e-4c31-11e7-8623-faa2ce875fe8.png)

**Comment by crazy-seb** [comment]
Tu pourrais m'envoyer un export de la configuration des ACF ?
J'en ai besoin pour remplir les champs.
Merci

**Comment by jihaisse** [comment]
Voilà l'export XML d'ACF.
J'espère que ça va fonctionner.

Le lun. 24 juil. 2017 à 17:05, crazy-seb <notifications@github.com> a
écrit :

**Comment by crazy-seb** [comment]
T'as oublié la pièce jointe^^

**Comment by crazy-seb** [comment]
Pull request #11
